%% DOWNLOADDATA
% Download data attributable to the paper "Intermittent treatment of 
% BRAFV600E melanoma cells delays resistance by adaptive resensitization to 
% drug rechallenge" by Kavran et al. 2022, PNAS.

%% DOSE RESPONSE
websave( ...
    "kavran_3day_cellcounts.csv", ...
    "https://raw.githubusercontent.com/andykavran/Intermittent_Drug_Treatment/master/data/intermittent_dose_response.csv" ...
)

%% GROWTH CURVE
websave( ...
    "kavran_28day_treatments.csv", ...
    "https://raw.githubusercontent.com/andykavran/Intermittent_Drug_Treatment/master/data/fig2_growth_curve_data.csv" ...
)